
    - name: ansible to copy a repo 
      ansible.builtin.copy: 
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo 

    - name: ansible to  install a package 
      ansible.builtin.package: 
        name: mongodb-org
        state: present  

    - name: Replace text in file
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'


    - name: ansible to restart a package 
      ansible.builtin.service: 
         name: mongod 
         state: restarted   

             