- name: Copy catalogue service
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service  

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart catalogue service
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes
