- name: Create roboshop system user
  ansible.builtin.user:
    name: roboshop
    system: yes
    home: /app
    shell: /sbin/nologin
    create_home: yes  

- name: ansible to delete app directory 
  ansible.builtin.file: 
    path: /app 
    state: absent 

- name: Create /app directory
  ansible.builtin.file:
    path: /app
    state: directory
    owner: roboshop
    group: roboshop
    mode: '0755'

- name: delete catalogue zip file
  ansible.builtin.file:
    path: /tmp/catalogue.zip
    state: absent

- name: download catalogue
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
    dest: /tmp/catalogue.zip

- name: unarchive catalogue
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes
